version: "2"
services:
    jboss-eap-host:
        build :
            context: ./jboss-eap-host
            dockerfile: eap-host
        environment:
            - JBOSS_DOMAIN_ADDRESS=${JBOSS_DOMAIN_ADDRESS}
            - JBOSS_DOMAIN_PORT=${JBOSS_DOMAIN_PORT}
            - JBOSS_DOMAIN_USER=${JBOSS_DOMAIN_USER}